version: '3.3'
services:

  probe:
    build:
      context: ./raspi-gpio
      dockerfile: Dockerfile 
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    entrypoint: /bin/bash
    volumes:
      - probevol:/appl
      - /dev/gpiomem:/dev/gpiomem
      - /dev/mem:/dev/mem
    #environment:
      #- --cap-add SYS_RAWIO

  web:
    image: nginx
    volumes:
      - ./site-content:/usr/share/nginx/html
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
 
 
  db:
    image: hypriot/rpi-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '33306:3306'
    expose:
      # Opens port 3306 on the container
      - '33306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
 
 
  mosquitto:
    image: eclipse-mosquitto
    #network_mode: host
    ports:
      - "1883:1883"
    #expose:
     #- '1883'
    volumes:
      - ./mqtt-broker/conf:/mosquitto/config
      - ./mqtt-broker/data:/mosquitto/data
      - ./mqtt-broker/log:/mosquitto/log


# Names our volume
volumes:
  my-db:
  probevol: